os: osx
language: node_js
node_js: node

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test
  - yarn package

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  draft: true

branches:
  only:
    - master
