os: osx
osx_image: xcode10
language: node_js
node_js: 10

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test
  - yarn package

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true

branches:
  only:
    - master
